/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AnalyticsTask } from "./AnalyticsTask";
import { AnalyticsTaskCountArgs } from "./AnalyticsTaskCountArgs";
import { AnalyticsTaskFindManyArgs } from "./AnalyticsTaskFindManyArgs";
import { AnalyticsTaskFindUniqueArgs } from "./AnalyticsTaskFindUniqueArgs";
import { DeleteAnalyticsTaskArgs } from "./DeleteAnalyticsTaskArgs";
import { AnalyticsTaskService } from "../analyticsTask.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AnalyticsTask)
export class AnalyticsTaskResolverBase {
  constructor(
    protected readonly service: AnalyticsTaskService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AnalyticsTask",
    action: "read",
    possession: "any",
  })
  async _analyticsTasksMeta(
    @graphql.Args() args: AnalyticsTaskCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AnalyticsTask])
  @nestAccessControl.UseRoles({
    resource: "AnalyticsTask",
    action: "read",
    possession: "any",
  })
  async analyticsTasks(
    @graphql.Args() args: AnalyticsTaskFindManyArgs
  ): Promise<AnalyticsTask[]> {
    return this.service.analyticsTasks(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AnalyticsTask, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AnalyticsTask",
    action: "read",
    possession: "own",
  })
  async analyticsTask(
    @graphql.Args() args: AnalyticsTaskFindUniqueArgs
  ): Promise<AnalyticsTask | null> {
    const result = await this.service.analyticsTask(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AnalyticsTask)
  @nestAccessControl.UseRoles({
    resource: "AnalyticsTask",
    action: "delete",
    possession: "any",
  })
  async deleteAnalyticsTask(
    @graphql.Args() args: DeleteAnalyticsTaskArgs
  ): Promise<AnalyticsTask | null> {
    try {
      return await this.service.deleteAnalyticsTask(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
