/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AnalyticsProspect } from "./AnalyticsProspect";
import { AnalyticsProspectCountArgs } from "./AnalyticsProspectCountArgs";
import { AnalyticsProspectFindManyArgs } from "./AnalyticsProspectFindManyArgs";
import { AnalyticsProspectFindUniqueArgs } from "./AnalyticsProspectFindUniqueArgs";
import { DeleteAnalyticsProspectArgs } from "./DeleteAnalyticsProspectArgs";
import { AnalyticsProspectService } from "../analyticsProspect.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AnalyticsProspect)
export class AnalyticsProspectResolverBase {
  constructor(
    protected readonly service: AnalyticsProspectService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AnalyticsProspect",
    action: "read",
    possession: "any",
  })
  async _analyticsProspectsMeta(
    @graphql.Args() args: AnalyticsProspectCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AnalyticsProspect])
  @nestAccessControl.UseRoles({
    resource: "AnalyticsProspect",
    action: "read",
    possession: "any",
  })
  async analyticsProspects(
    @graphql.Args() args: AnalyticsProspectFindManyArgs
  ): Promise<AnalyticsProspect[]> {
    return this.service.analyticsProspects(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AnalyticsProspect, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AnalyticsProspect",
    action: "read",
    possession: "own",
  })
  async analyticsProspect(
    @graphql.Args() args: AnalyticsProspectFindUniqueArgs
  ): Promise<AnalyticsProspect | null> {
    const result = await this.service.analyticsProspect(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AnalyticsProspect)
  @nestAccessControl.UseRoles({
    resource: "AnalyticsProspect",
    action: "delete",
    possession: "any",
  })
  async deleteAnalyticsProspect(
    @graphql.Args() args: DeleteAnalyticsProspectArgs
  ): Promise<AnalyticsProspect | null> {
    try {
      return await this.service.deleteAnalyticsProspect(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
