/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AnalyticsBusinessService } from "../analyticsBusiness.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AnalyticsBusinessCreateInput } from "./AnalyticsBusinessCreateInput";
import { AnalyticsBusiness } from "./AnalyticsBusiness";
import { AnalyticsBusinessFindManyArgs } from "./AnalyticsBusinessFindManyArgs";
import { AnalyticsBusinessWhereUniqueInput } from "./AnalyticsBusinessWhereUniqueInput";
import { AnalyticsBusinessUpdateInput } from "./AnalyticsBusinessUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AnalyticsBusinessControllerBase {
  constructor(
    protected readonly service: AnalyticsBusinessService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AnalyticsBusiness })
  @nestAccessControl.UseRoles({
    resource: "AnalyticsBusiness",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAnalyticsBusiness(
    @common.Body() data: AnalyticsBusinessCreateInput
  ): Promise<AnalyticsBusiness> {
    return await this.service.createAnalyticsBusiness({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AnalyticsBusiness] })
  @ApiNestedQuery(AnalyticsBusinessFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AnalyticsBusiness",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async analyticsBusinesses(
    @common.Req() request: Request
  ): Promise<AnalyticsBusiness[]> {
    const args = plainToClass(AnalyticsBusinessFindManyArgs, request.query);
    return this.service.analyticsBusinesses({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AnalyticsBusiness })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AnalyticsBusiness",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async analyticsBusiness(
    @common.Param() params: AnalyticsBusinessWhereUniqueInput
  ): Promise<AnalyticsBusiness | null> {
    const result = await this.service.analyticsBusiness({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AnalyticsBusiness })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AnalyticsBusiness",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAnalyticsBusiness(
    @common.Param() params: AnalyticsBusinessWhereUniqueInput,
    @common.Body() data: AnalyticsBusinessUpdateInput
  ): Promise<AnalyticsBusiness | null> {
    try {
      return await this.service.updateAnalyticsBusiness({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AnalyticsBusiness })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AnalyticsBusiness",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAnalyticsBusiness(
    @common.Param() params: AnalyticsBusinessWhereUniqueInput
  ): Promise<AnalyticsBusiness | null> {
    try {
      return await this.service.deleteAnalyticsBusiness({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
