/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AnalyticsBusiness } from "./AnalyticsBusiness";
import { AnalyticsBusinessCountArgs } from "./AnalyticsBusinessCountArgs";
import { AnalyticsBusinessFindManyArgs } from "./AnalyticsBusinessFindManyArgs";
import { AnalyticsBusinessFindUniqueArgs } from "./AnalyticsBusinessFindUniqueArgs";
import { DeleteAnalyticsBusinessArgs } from "./DeleteAnalyticsBusinessArgs";
import { AnalyticsBusinessService } from "../analyticsBusiness.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AnalyticsBusiness)
export class AnalyticsBusinessResolverBase {
  constructor(
    protected readonly service: AnalyticsBusinessService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AnalyticsBusiness",
    action: "read",
    possession: "any",
  })
  async _analyticsBusinessesMeta(
    @graphql.Args() args: AnalyticsBusinessCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AnalyticsBusiness])
  @nestAccessControl.UseRoles({
    resource: "AnalyticsBusiness",
    action: "read",
    possession: "any",
  })
  async analyticsBusinesses(
    @graphql.Args() args: AnalyticsBusinessFindManyArgs
  ): Promise<AnalyticsBusiness[]> {
    return this.service.analyticsBusinesses(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AnalyticsBusiness, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AnalyticsBusiness",
    action: "read",
    possession: "own",
  })
  async analyticsBusiness(
    @graphql.Args() args: AnalyticsBusinessFindUniqueArgs
  ): Promise<AnalyticsBusiness | null> {
    const result = await this.service.analyticsBusiness(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AnalyticsBusiness)
  @nestAccessControl.UseRoles({
    resource: "AnalyticsBusiness",
    action: "delete",
    possession: "any",
  })
  async deleteAnalyticsBusiness(
    @graphql.Args() args: DeleteAnalyticsBusinessArgs
  ): Promise<AnalyticsBusiness | null> {
    try {
      return await this.service.deleteAnalyticsBusiness(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
