/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AnalyticsLead } from "./AnalyticsLead";
import { AnalyticsLeadCountArgs } from "./AnalyticsLeadCountArgs";
import { AnalyticsLeadFindManyArgs } from "./AnalyticsLeadFindManyArgs";
import { AnalyticsLeadFindUniqueArgs } from "./AnalyticsLeadFindUniqueArgs";
import { DeleteAnalyticsLeadArgs } from "./DeleteAnalyticsLeadArgs";
import { AnalyticsLeadService } from "../analyticsLead.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AnalyticsLead)
export class AnalyticsLeadResolverBase {
  constructor(
    protected readonly service: AnalyticsLeadService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AnalyticsLead",
    action: "read",
    possession: "any",
  })
  async _analyticsLeadsMeta(
    @graphql.Args() args: AnalyticsLeadCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AnalyticsLead])
  @nestAccessControl.UseRoles({
    resource: "AnalyticsLead",
    action: "read",
    possession: "any",
  })
  async analyticsLeads(
    @graphql.Args() args: AnalyticsLeadFindManyArgs
  ): Promise<AnalyticsLead[]> {
    return this.service.analyticsLeads(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AnalyticsLead, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AnalyticsLead",
    action: "read",
    possession: "own",
  })
  async analyticsLead(
    @graphql.Args() args: AnalyticsLeadFindUniqueArgs
  ): Promise<AnalyticsLead | null> {
    const result = await this.service.analyticsLead(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AnalyticsLead)
  @nestAccessControl.UseRoles({
    resource: "AnalyticsLead",
    action: "delete",
    possession: "any",
  })
  async deleteAnalyticsLead(
    @graphql.Args() args: DeleteAnalyticsLeadArgs
  ): Promise<AnalyticsLead | null> {
    try {
      return await this.service.deleteAnalyticsLead(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
