/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProfessionalService } from "../professional.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProfessionalCreateInput } from "./ProfessionalCreateInput";
import { Professional } from "./Professional";
import { ProfessionalFindManyArgs } from "./ProfessionalFindManyArgs";
import { ProfessionalWhereUniqueInput } from "./ProfessionalWhereUniqueInput";
import { ProfessionalUpdateInput } from "./ProfessionalUpdateInput";
import { ProspectFindManyArgs } from "../../prospect/base/ProspectFindManyArgs";
import { Prospect } from "../../prospect/base/Prospect";
import { ProspectWhereUniqueInput } from "../../prospect/base/ProspectWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProfessionalControllerBase {
  constructor(
    protected readonly service: ProfessionalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Professional })
  @nestAccessControl.UseRoles({
    resource: "Professional",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProfessional(
    @common.Body() data: ProfessionalCreateInput
  ): Promise<Professional> {
    return await this.service.createProfessional({
      data: {
        ...data,

        business: data.business
          ? {
              connect: data.business,
            }
          : undefined,
      },
      select: {
        business: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Professional] })
  @ApiNestedQuery(ProfessionalFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Professional",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async professionals(@common.Req() request: Request): Promise<Professional[]> {
    const args = plainToClass(ProfessionalFindManyArgs, request.query);
    return this.service.professionals({
      ...args,
      select: {
        business: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Professional })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Professional",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async professional(
    @common.Param() params: ProfessionalWhereUniqueInput
  ): Promise<Professional | null> {
    const result = await this.service.professional({
      where: params,
      select: {
        business: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Professional })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Professional",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProfessional(
    @common.Param() params: ProfessionalWhereUniqueInput,
    @common.Body() data: ProfessionalUpdateInput
  ): Promise<Professional | null> {
    try {
      return await this.service.updateProfessional({
        where: params,
        data: {
          ...data,

          business: data.business
            ? {
                connect: data.business,
              }
            : undefined,
        },
        select: {
          business: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          phoneNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Professional })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Professional",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProfessional(
    @common.Param() params: ProfessionalWhereUniqueInput
  ): Promise<Professional | null> {
    try {
      return await this.service.deleteProfessional({
        where: params,
        select: {
          business: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          phoneNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/prospects")
  @ApiNestedQuery(ProspectFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Prospect",
    action: "read",
    possession: "any",
  })
  async findProspects(
    @common.Req() request: Request,
    @common.Param() params: ProfessionalWhereUniqueInput
  ): Promise<Prospect[]> {
    const query = plainToClass(ProspectFindManyArgs, request.query);
    const results = await this.service.findProspects(params.id, {
      ...query,
      select: {
        business: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        lead: {
          select: {
            id: true,
          },
        },

        professional: {
          select: {
            id: true,
          },
        },

        taskList: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/prospects")
  @nestAccessControl.UseRoles({
    resource: "Professional",
    action: "update",
    possession: "any",
  })
  async connectProspects(
    @common.Param() params: ProfessionalWhereUniqueInput,
    @common.Body() body: ProspectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      prospects: {
        connect: body,
      },
    };
    await this.service.updateProfessional({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/prospects")
  @nestAccessControl.UseRoles({
    resource: "Professional",
    action: "update",
    possession: "any",
  })
  async updateProspects(
    @common.Param() params: ProfessionalWhereUniqueInput,
    @common.Body() body: ProspectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      prospects: {
        set: body,
      },
    };
    await this.service.updateProfessional({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/prospects")
  @nestAccessControl.UseRoles({
    resource: "Professional",
    action: "update",
    possession: "any",
  })
  async disconnectProspects(
    @common.Param() params: ProfessionalWhereUniqueInput,
    @common.Body() body: ProspectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      prospects: {
        disconnect: body,
      },
    };
    await this.service.updateProfessional({
      where: params,
      data,
      select: { id: true },
    });
  }
}
