/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Professional } from "./Professional";
import { ProfessionalCountArgs } from "./ProfessionalCountArgs";
import { ProfessionalFindManyArgs } from "./ProfessionalFindManyArgs";
import { ProfessionalFindUniqueArgs } from "./ProfessionalFindUniqueArgs";
import { CreateProfessionalArgs } from "./CreateProfessionalArgs";
import { UpdateProfessionalArgs } from "./UpdateProfessionalArgs";
import { DeleteProfessionalArgs } from "./DeleteProfessionalArgs";
import { ProspectFindManyArgs } from "../../prospect/base/ProspectFindManyArgs";
import { Prospect } from "../../prospect/base/Prospect";
import { Business } from "../../business/base/Business";
import { ProfessionalService } from "../professional.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Professional)
export class ProfessionalResolverBase {
  constructor(
    protected readonly service: ProfessionalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Professional",
    action: "read",
    possession: "any",
  })
  async _professionalsMeta(
    @graphql.Args() args: ProfessionalCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Professional])
  @nestAccessControl.UseRoles({
    resource: "Professional",
    action: "read",
    possession: "any",
  })
  async professionals(
    @graphql.Args() args: ProfessionalFindManyArgs
  ): Promise<Professional[]> {
    return this.service.professionals(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Professional, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Professional",
    action: "read",
    possession: "own",
  })
  async professional(
    @graphql.Args() args: ProfessionalFindUniqueArgs
  ): Promise<Professional | null> {
    const result = await this.service.professional(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Professional)
  @nestAccessControl.UseRoles({
    resource: "Professional",
    action: "create",
    possession: "any",
  })
  async createProfessional(
    @graphql.Args() args: CreateProfessionalArgs
  ): Promise<Professional> {
    return await this.service.createProfessional({
      ...args,
      data: {
        ...args.data,

        business: args.data.business
          ? {
              connect: args.data.business,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Professional)
  @nestAccessControl.UseRoles({
    resource: "Professional",
    action: "update",
    possession: "any",
  })
  async updateProfessional(
    @graphql.Args() args: UpdateProfessionalArgs
  ): Promise<Professional | null> {
    try {
      return await this.service.updateProfessional({
        ...args,
        data: {
          ...args.data,

          business: args.data.business
            ? {
                connect: args.data.business,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Professional)
  @nestAccessControl.UseRoles({
    resource: "Professional",
    action: "delete",
    possession: "any",
  })
  async deleteProfessional(
    @graphql.Args() args: DeleteProfessionalArgs
  ): Promise<Professional | null> {
    try {
      return await this.service.deleteProfessional(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Prospect], { name: "prospects" })
  @nestAccessControl.UseRoles({
    resource: "Prospect",
    action: "read",
    possession: "any",
  })
  async findProspects(
    @graphql.Parent() parent: Professional,
    @graphql.Args() args: ProspectFindManyArgs
  ): Promise<Prospect[]> {
    const results = await this.service.findProspects(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Business, {
    nullable: true,
    name: "business",
  })
  @nestAccessControl.UseRoles({
    resource: "Business",
    action: "read",
    possession: "any",
  })
  async getBusiness(
    @graphql.Parent() parent: Professional
  ): Promise<Business | null> {
    const result = await this.service.getBusiness(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
