/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProspectService } from "../prospect.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProspectCreateInput } from "./ProspectCreateInput";
import { Prospect } from "./Prospect";
import { ProspectFindManyArgs } from "./ProspectFindManyArgs";
import { ProspectWhereUniqueInput } from "./ProspectWhereUniqueInput";
import { ProspectUpdateInput } from "./ProspectUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProspectControllerBase {
  constructor(
    protected readonly service: ProspectService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Prospect })
  @nestAccessControl.UseRoles({
    resource: "Prospect",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProspect(
    @common.Body() data: ProspectCreateInput
  ): Promise<Prospect> {
    return await this.service.createProspect({
      data: {
        ...data,

        business: data.business
          ? {
              connect: data.business,
            }
          : undefined,

        lead: data.lead
          ? {
              connect: data.lead,
            }
          : undefined,

        professional: data.professional
          ? {
              connect: data.professional,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        business: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        lead: {
          select: {
            id: true,
          },
        },

        professional: {
          select: {
            id: true,
          },
        },

        taskList: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Prospect] })
  @ApiNestedQuery(ProspectFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Prospect",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async prospects(@common.Req() request: Request): Promise<Prospect[]> {
    const args = plainToClass(ProspectFindManyArgs, request.query);
    return this.service.prospects({
      ...args,
      select: {
        business: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        lead: {
          select: {
            id: true,
          },
        },

        professional: {
          select: {
            id: true,
          },
        },

        taskList: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Prospect })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Prospect",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async prospect(
    @common.Param() params: ProspectWhereUniqueInput
  ): Promise<Prospect | null> {
    const result = await this.service.prospect({
      where: params,
      select: {
        business: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        lead: {
          select: {
            id: true,
          },
        },

        professional: {
          select: {
            id: true,
          },
        },

        taskList: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Prospect })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Prospect",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProspect(
    @common.Param() params: ProspectWhereUniqueInput,
    @common.Body() data: ProspectUpdateInput
  ): Promise<Prospect | null> {
    try {
      return await this.service.updateProspect({
        where: params,
        data: {
          ...data,

          business: data.business
            ? {
                connect: data.business,
              }
            : undefined,

          lead: data.lead
            ? {
                connect: data.lead,
              }
            : undefined,

          professional: data.professional
            ? {
                connect: data.professional,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          business: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,

          lead: {
            select: {
              id: true,
            },
          },

          professional: {
            select: {
              id: true,
            },
          },

          taskList: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Prospect })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Prospect",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProspect(
    @common.Param() params: ProspectWhereUniqueInput
  ): Promise<Prospect | null> {
    try {
      return await this.service.deleteProspect({
        where: params,
        select: {
          business: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,

          lead: {
            select: {
              id: true,
            },
          },

          professional: {
            select: {
              id: true,
            },
          },

          taskList: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
