/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AnalyticsSubscription } from "./AnalyticsSubscription";
import { AnalyticsSubscriptionCountArgs } from "./AnalyticsSubscriptionCountArgs";
import { AnalyticsSubscriptionFindManyArgs } from "./AnalyticsSubscriptionFindManyArgs";
import { AnalyticsSubscriptionFindUniqueArgs } from "./AnalyticsSubscriptionFindUniqueArgs";
import { DeleteAnalyticsSubscriptionArgs } from "./DeleteAnalyticsSubscriptionArgs";
import { AnalyticsSubscriptionService } from "../analyticsSubscription.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AnalyticsSubscription)
export class AnalyticsSubscriptionResolverBase {
  constructor(
    protected readonly service: AnalyticsSubscriptionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AnalyticsSubscription",
    action: "read",
    possession: "any",
  })
  async _analyticsSubscriptionsMeta(
    @graphql.Args() args: AnalyticsSubscriptionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AnalyticsSubscription])
  @nestAccessControl.UseRoles({
    resource: "AnalyticsSubscription",
    action: "read",
    possession: "any",
  })
  async analyticsSubscriptions(
    @graphql.Args() args: AnalyticsSubscriptionFindManyArgs
  ): Promise<AnalyticsSubscription[]> {
    return this.service.analyticsSubscriptions(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AnalyticsSubscription, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AnalyticsSubscription",
    action: "read",
    possession: "own",
  })
  async analyticsSubscription(
    @graphql.Args() args: AnalyticsSubscriptionFindUniqueArgs
  ): Promise<AnalyticsSubscription | null> {
    const result = await this.service.analyticsSubscription(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AnalyticsSubscription)
  @nestAccessControl.UseRoles({
    resource: "AnalyticsSubscription",
    action: "delete",
    possession: "any",
  })
  async deleteAnalyticsSubscription(
    @graphql.Args() args: DeleteAnalyticsSubscriptionArgs
  ): Promise<AnalyticsSubscription | null> {
    try {
      return await this.service.deleteAnalyticsSubscription(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
