/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AnalyticsSubscriptionService } from "../analyticsSubscription.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AnalyticsSubscriptionCreateInput } from "./AnalyticsSubscriptionCreateInput";
import { AnalyticsSubscription } from "./AnalyticsSubscription";
import { AnalyticsSubscriptionFindManyArgs } from "./AnalyticsSubscriptionFindManyArgs";
import { AnalyticsSubscriptionWhereUniqueInput } from "./AnalyticsSubscriptionWhereUniqueInput";
import { AnalyticsSubscriptionUpdateInput } from "./AnalyticsSubscriptionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AnalyticsSubscriptionControllerBase {
  constructor(
    protected readonly service: AnalyticsSubscriptionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AnalyticsSubscription })
  @nestAccessControl.UseRoles({
    resource: "AnalyticsSubscription",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAnalyticsSubscription(
    @common.Body() data: AnalyticsSubscriptionCreateInput
  ): Promise<AnalyticsSubscription> {
    return await this.service.createAnalyticsSubscription({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AnalyticsSubscription] })
  @ApiNestedQuery(AnalyticsSubscriptionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AnalyticsSubscription",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async analyticsSubscriptions(
    @common.Req() request: Request
  ): Promise<AnalyticsSubscription[]> {
    const args = plainToClass(AnalyticsSubscriptionFindManyArgs, request.query);
    return this.service.analyticsSubscriptions({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AnalyticsSubscription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AnalyticsSubscription",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async analyticsSubscription(
    @common.Param() params: AnalyticsSubscriptionWhereUniqueInput
  ): Promise<AnalyticsSubscription | null> {
    const result = await this.service.analyticsSubscription({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AnalyticsSubscription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AnalyticsSubscription",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAnalyticsSubscription(
    @common.Param() params: AnalyticsSubscriptionWhereUniqueInput,
    @common.Body() data: AnalyticsSubscriptionUpdateInput
  ): Promise<AnalyticsSubscription | null> {
    try {
      return await this.service.updateAnalyticsSubscription({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AnalyticsSubscription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AnalyticsSubscription",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAnalyticsSubscription(
    @common.Param() params: AnalyticsSubscriptionWhereUniqueInput
  ): Promise<AnalyticsSubscription | null> {
    try {
      return await this.service.deleteAnalyticsSubscription({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
