/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BusinessCreateNestedManyWithoutAddressesInput } from "./BusinessCreateNestedManyWithoutAddressesInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { LeadCreateNestedManyWithoutAddressesInput } from "./LeadCreateNestedManyWithoutAddressesInput";

@InputType()
class AddressCreateInput {
  @ApiProperty({
    required: false,
    type: () => BusinessCreateNestedManyWithoutAddressesInput,
  })
  @ValidateNested()
  @Type(() => BusinessCreateNestedManyWithoutAddressesInput)
  @IsOptional()
  @Field(() => BusinessCreateNestedManyWithoutAddressesInput, {
    nullable: true,
  })
  businesses?: BusinessCreateNestedManyWithoutAddressesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  city?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  country?: string | null;

  @ApiProperty({
    required: false,
    type: () => LeadCreateNestedManyWithoutAddressesInput,
  })
  @ValidateNested()
  @Type(() => LeadCreateNestedManyWithoutAddressesInput)
  @IsOptional()
  @Field(() => LeadCreateNestedManyWithoutAddressesInput, {
    nullable: true,
  })
  leads?: LeadCreateNestedManyWithoutAddressesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  postalCode?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  state?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  street?: string | null;
}

export { AddressCreateInput as AddressCreateInput };
